services:
  app:
    image: chrisfcushman/bitcoinbros:latest
    container_name: app
    ports:
      - "3000:3000"
    volumes:
      - /var/run/tappd.sock:/var/run/tappd.sock
    environment:
      - GITHUB_TOKEN=${GITHUB_TOKEN}
      - BOT_TOKEN=${BOT_TOKEN}
      - NO_COINERS_JOIN_LINK=${NO_COINERS_JOIN_LINK}
      - PRAWNS_JOIN_LINK=${PRAWNS_JOIN_LINK}
      - SHRIMPS_JOIN_LINK=${SHRIMPS_JOIN_LINK}
      - CRABS_JOIN_LINK=${CRABS_JOIN_LINK}
      - OCTOPUSES_JOIN_LINK=${OCTOPUSES_JOIN_LINK}
      - DOLPHINS_JOIN_LINK=${DOLPHINS_JOIN_LINK}
      - SHARKS_JOIN_LINK=${SHARKS_JOIN_LINK}
      - WHALES_JOIN_LINK=${WHALES_JOIN_LINK}
    restart: unless-stopped